version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

    assignees:
      - "jag-k"

  # Maintain dependencies for Poetry
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

    # Include a list of updated dependencies
    # with a prefix determined by the dependency group
    commit-message:
      prefix: "poetry"
      prefix-development: "poetry dev"
      include: "scope"

    assignees:
      - "jag-k"
